const styles = {
  container: {
    maxWidth: 700,
    margin: "40px auto",
    padding: 30,
    backgroundColor: "#f9fafb",
    borderRadius: 12,
    boxShadow: "0 10px 30px rgba(0,0,0,0.1)",
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
  },
  header: {
    textAlign: "center",
    color: "#2c3e50",
    marginBottom: 25,
    fontWeight: "700",
    fontSize: 28,
  },
  radioGroup: {
    display: "flex",
    flexDirection: "column",
    marginBottom: 25,
    gap: 14,
    color: "#34495e",
    fontWeight: 600,
  },
  textarea: {
    width: "100%",
    borderRadius: 8,
    border: "1.8px solid #d1d5db",
    padding: 15,
    fontFamily: "monospace",
    fontSize: 16,
    transition: "border-color 0.3s ease",
    resize: "vertical",
  },
  input: {
    width: "100%",
    padding: 12,
    borderRadius: 8,
    border: "1.8px solid #d1d5db",
    fontSize: 16,
    transition: "border-color 0.3s ease",
    marginBottom: 14,
  },
  button: {
    backgroundColor: "#3498db",
    color: "white",
    padding: "12px 28px",
    fontWeight: "600",
    border: "none",
    borderRadius: 8,
    cursor: "pointer",
    fontSize: 16,
    boxShadow: "0 5px 15px rgba(52, 152, 219, 0.3)",
    transition: "background-color 0.3s ease",
  },
  buttonDisabled: {
    backgroundColor: "#a2b4c7",
    cursor: "not-allowed",
    boxShadow: "none",
  },
  results: {
    marginTop: 40,
    color: "#2c3e50",
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
  },
  resultsHeader: {
    fontWeight: "800",
    fontSize: 24,
    marginBottom: 24,
    paddingBottom: 8,
    borderRadius: 8,
    background: "linear-gradient(90deg, #f0f4f8, #dbe9fb)",
    color: "#34495e",
    boxShadow: "inset 0 -3px 8px rgba(52, 152, 219, 0.15)",
    textAlign: "center",
    letterSpacing: "0.04em",
  },
  resultList: {
    listStyle: "none",
    paddingLeft: 0,
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(180px, 1fr))",
    gap: 24,
  },
  resultItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    borderRadius: 16,
    padding: 14,
    backgroundColor: "#f9fbfd",
    boxShadow: "0 4px 14px rgba(0,0,0,0.07)",
    transition: "transform 0.25s ease, box-shadow 0.25s ease",
    cursor: "pointer",
  },
  thumbnail: {
    maxHeight: 100,
    maxWidth: "100%",
    borderRadius: 12,
    objectFit: "cover",
    marginBottom: 12,
  },
  resultLink: {
    color: "#2c3e50",
    fontWeight: "700",
    fontSize: 15,
    textDecoration: "none",
    wordBreak: "break-word",
    textAlign: "center",
    userSelect: "text",
    transition: "color 0.25s ease",
  },
  noResults: {
    fontStyle: "italic",
    color: "#7f8c8d",
    fontSize: 16,
    marginTop: 10,
    textAlign: "center",
  },
};


export default styles;